// UI strings for the social layer (share, challenges, streaks, badges, leagues,
// the You page). Merged into i18n/strings.js under `social` — t('social.…').

export const social = {
  en: {
    nav: { you: 'You', leagues: 'Leagues' },
    hubWeek: 'WEEK',
    share: {
      shareResult: 'Share & challenge',
      copyText: 'Copy', copied: 'Copied — paste it in the chat',
      whatsapp: 'WhatsApp', teams: 'Teams', image: 'Image', link: 'Link',
      preview: 'What your mates will see',
      shareDay: 'Share my matchday',
      dayCopied: 'Matchday copied — paste it in the chat',
    },
    challenge: {
      beat: '{name} scored {score} on today’s {game}.',
      beatCta: 'Beat it',
      beatDay: '{name} played Matchday {m}: {n} dailies, {pts} pts.',
      beatDayCta: 'Beat their matchday',
      old: '{name} sent you Matchday {m} — today’s puzzle is new, but their score still counts in your head-to-head.',
      someone: 'A mate',
      vs: 'VS',
      youWin: 'YOU WIN', youLose: 'THEY WIN', draw: 'LEVEL',
      you: 'You',
      replyWin: 'Rub it in',
      replyLose: 'Ask for a rematch',
      waiting: 'Waiting on your result',
      dismiss: 'Dismiss',
    },
    global: {
      beat: 'You beat {pc}% of today’s players',
      first: 'You’re one of the first to play today',
      players: '{n} played today',
      playing: '{n} playing today',
      playingChip: 'PLAYING TODAY',
      howEveryone: 'How everyone did today',
      offline: 'Global stats appear when you’re online',
    },
    streak: {
      days: '{n}-day streak',
      startToday: 'Play a daily to start a streak',
      keepAlive: 'Come back tomorrow to make it {n}',
      atRisk: 'Your {n}-day streak is on the line — play any daily today',
      atRiskShort: '🔥 {n} on the line — play today',
      freezes: '{n} freeze banked',
      freezesMany: '{n} freezes banked',
      nextFreeze: 'Freeze in {n} days',
      freezeUsed: 'A streak freeze saved your streak',
      nextMatchday: 'Next matchday in {t}',
      best: 'Best {n}',
      freezeHelp: 'Every 7 days of streak banks a freeze (max 2). Miss a day and a freeze covers it automatically.',
    },
    reminder: {
      button: 'Remind me',
      title: 'Never miss a matchday',
      body: 'Add a recurring reminder to your calendar. Most people play at lunch.',
      time: 'Time', weekdays: 'Weekdays only', everyday: 'Every day',
      ics: 'Outlook / Apple (.ics)', google: 'Google Calendar', outlookWeb: 'Outlook web',
      done: 'Reminder file downloaded — open it to add to your calendar',
      close: 'Done',
    },
    badges: {
      unlocked: 'BADGE UNLOCKED',
      cabinet: 'Trophy cabinet',
      earned: '{n} of {total} earned',
      locked: 'Locked',
      names: {
        'first-whistle': ['First whistle', 'Play your first daily'],
        'hat-trick': ['Hat-trick', 'Play 3 dailies in one day'],
        'full-squad': ['Full squad', 'Play every game at least once'],
        'perfect-day': ['Perfect day', 'Play every daily in one day'],
        treble: ['The treble', 'Three perfect days'],
        'streak-3': ['On a run', '3-day streak'],
        'streak-7': ['Week in, week out', '7-day streak'],
        'streak-30': ['Ever-present', '30-day streak'],
        'streak-100': ['Club legend', '100-day streak'],
        fifty: ['Fifty up', 'Play 50 dailies'],
        century: ['Centurion', 'Play 100 dailies'],
        'tenable-ten': ['Full house', '10/10 on Tenable'],
        'wordle-two': ['Sniper', 'Solve Wordle in 2'],
        'connections-flawless': ['Clean sheet', 'Connections with no mistakes'],
        'pointless-low': ['Obscure knowledge', 'Win Pointless on 30 or fewer'],
        'early-kickoff': ['Early kick-off', 'Play before 8am'],
        'late-kickoff': ['Late kick-off', 'Play after 11pm'],
        'top-ten': ['Top 10%', 'Beat 90% of players on a daily'],
        messenger: ['Messenger', 'Share a result'],
        recruiter: ['Scout', 'Share 5 results'],
        'derby-win': ['Derby day', 'Beat a mate head-to-head'],
        'derby-king': ['Derby king', '10 head-to-head wins'],
        gaffer: ['Gaffer', 'Start a league'],
        champion: ['Champions', 'Win a league week'],
      },
    },
    me: {
      title: 'Your dressing room',
      subtitle: 'Your streaks, records, rivals and leagues',
      nickname: 'Your name', nicknamePh: 'e.g. Tom',
      nicknameHelp: 'Shown to mates in challenges and league tables.',
      save: 'Save', saved: 'Saved',
      streak: 'Matchday streak',
      thisWeek: 'This week', pts: 'pts', played: 'played', perfect: 'perfect days',
      calendar: 'Last 16 weeks', less: 'Less', more: 'More',
      records: 'Records',
      recGame: 'Game', recPlayed: 'P', recWin: 'Win %', recBest: 'Best', recAvg: 'Avg', recStreak: 'Streak',
      recTop: 'Best %',
      noRecords: 'Play a daily and your records start here.',
      rivals: 'Head-to-head',
      rivalsEmpty: 'When a mate sends you a result link, they appear here — with your record against them.',
      rivalsW: 'W', rivalsD: 'D', rivalsL: 'L', rivalsPending: '{n} to play',
      leagues: 'Your leagues',
      openLeagues: 'Leagues →',
      transfer: 'Move to another device',
      transferBody: 'Your stats live in this browser. Make a code to carry streaks, records, rivals and leagues to your phone or work laptop.',
      makeCode: 'Make a transfer code',
      codeReady: 'Open this link on the other device (valid 24 hours):',
      codeShort: 'Or enter this code on the other device’s You page:',
      codeLong: 'Offline — copy this link instead:',
      copyLink: 'Copy link',
      enterCode: 'Have a code?', enterPh: 'ABC123', importBtn: 'Import',
      importConfirm: 'Bring in stats from another device? They’ll be merged with this one.',
      imported: 'Imported {n} results',
      importFailed: 'That code didn’t work — it may have expired',
      reminder: 'Daily reminder',
    },
    leagues: {
      title: 'Leagues',
      subtitle: 'A private weekly table for you and your mates. Points from every daily, reset each Monday.',
      mine: 'Your leagues',
      none: 'You’re not in a league yet.',
      create: 'Start a league', createPh: 'League name, e.g. Accounts FC', createBtn: 'Create',
      join: 'Join with a code', joinPh: 'Code', joinBtn: 'Join',
      needName: 'Pick a name first — it’s what your mates see in the table.',
      namePh: 'Your name',
      invite: 'Invite', inviteCopied: 'Invite copied — paste it in the group chat',
      inviteText: 'Join my Triviverse league "{name}" ⚽ Daily football trivia, weekly table, free. Code {code}',
      code: 'Code',
      week: 'This week', today: 'Today', allTime: 'All-time', lastWeek: 'Last week',
      pos: 'Pos', player: 'Player', pts: 'Pts', p: 'P', w: 'W', perfect: '★',
      you: 'you',
      rank: '{rank} of {n}',
      ptsBehind: '{n} pts off the top', leading: 'Top of the table', level: 'Level on top',
      nextUp: '{n} pts to catch {name}',
      champion: 'Last week’s champion',
      notPlayed: 'Not played yet',
      resetsIn: 'Table resets Monday',
      joinTitle: 'You’re invited',
      joinBody: '{n} players · weekly table · points from every daily',
      joinCta: 'Join league',
      notFound: 'No league with that code.',
      leave: 'Leave league', leaveConfirm: 'Leave this league? Your points stay in its history.',
      offline: 'Leagues need a connection. Your games still count locally.',
      scoring: 'Scoring: 10 per daily played, 25 per win, +5 per streak day (max +25), perfect day doubles the day.',
      members: '{n} players',
      open: 'Open',
      gamesToday: 'Today’s dailies',
    },
    errors: {
      name_required: 'Pick a name first.',
      league_name_required: 'Give the league a name.',
      too_many_leagues: 'You’ve started the maximum number of leagues.',
      too_many_memberships: 'You’re in the maximum number of leagues.',
      league_full: 'That league is full.',
      not_found: 'Not found.',
      generic: 'Something went wrong — try again.',
    },
  },
  es: {
    nav: { you: 'Tú', leagues: 'Ligas' },
    hubWeek: 'SEMANA',
    share: {
      shareResult: 'Compartir y retar',
      copyText: 'Copiar', copied: 'Copiado: pégalo en el chat',
      whatsapp: 'WhatsApp', teams: 'Teams', image: 'Imagen', link: 'Enlace',
      preview: 'Lo que verán tus amigos',
      shareDay: 'Compartir mi jornada',
      dayCopied: 'Jornada copiada: pégala en el chat',
    },
    challenge: {
      beat: '{name} hizo {score} en {game} de hoy.',
      beatCta: 'Supéralo',
      beatDay: '{name} jugó la Jornada {m}: {n} juegos, {pts} pts.',
      beatDayCta: 'Supera su jornada',
      old: '{name} te envió la Jornada {m}: el reto de hoy es otro, pero su resultado cuenta en vuestro cara a cara.',
      someone: 'Un amigo',
      vs: 'VS',
      youWin: 'GANAS', youLose: 'GANA', draw: 'EMPATE',
      you: 'Tú',
      replyWin: 'Restriégaselo',
      replyLose: 'Pide la revancha',
      waiting: 'Esperando tu resultado',
      dismiss: 'Cerrar',
    },
    global: {
      beat: 'Superas al {pc}% de los jugadores de hoy',
      first: 'Eres de los primeros en jugar hoy',
      players: '{n} jugaron hoy',
      playing: '{n} jugando hoy',
      playingChip: 'JUGANDO HOY',
      howEveryone: 'Cómo le fue a todos hoy',
      offline: 'Las estadísticas globales aparecen con conexión',
    },
    streak: {
      days: 'Racha de {n} días',
      startToday: 'Juega un diario para empezar una racha',
      keepAlive: 'Vuelve mañana para llegar a {n}',
      atRisk: 'Tu racha de {n} días está en juego: juega cualquier diario hoy',
      atRiskShort: '🔥 {n} en juego: juega hoy',
      freezes: '{n} comodín guardado',
      freezesMany: '{n} comodines guardados',
      nextFreeze: 'Comodín en {n} días',
      freezeUsed: 'Un comodín salvó tu racha',
      nextMatchday: 'Próxima jornada en {t}',
      best: 'Mejor {n}',
      freezeHelp: 'Cada 7 días de racha ganas un comodín (máx. 2). Si fallas un día, el comodín lo cubre solo.',
    },
    reminder: {
      button: 'Recordármelo',
      title: 'No te pierdas ninguna jornada',
      body: 'Añade un recordatorio periódico a tu calendario. La mayoría juega a la hora de comer.',
      time: 'Hora', weekdays: 'Solo entre semana', everyday: 'Todos los días',
      ics: 'Outlook / Apple (.ics)', google: 'Google Calendar', outlookWeb: 'Outlook web',
      done: 'Recordatorio descargado: ábrelo para añadirlo a tu calendario',
      close: 'Listo',
    },
    badges: {
      unlocked: 'INSIGNIA DESBLOQUEADA',
      cabinet: 'Vitrina de trofeos',
      earned: '{n} de {total} conseguidas',
      locked: 'Bloqueada',
      names: {
        'first-whistle': ['Pitido inicial', 'Juega tu primer diario'],
        'hat-trick': ['Hat-trick', 'Juega 3 diarios en un día'],
        'full-squad': ['Plantilla completa', 'Juega todos los juegos al menos una vez'],
        'perfect-day': ['Día perfecto', 'Juega todos los diarios en un día'],
        treble: ['El triplete', 'Tres días perfectos'],
        'streak-3': ['En racha', 'Racha de 3 días'],
        'streak-7': ['Semana tras semana', 'Racha de 7 días'],
        'streak-30': ['Fijo', 'Racha de 30 días'],
        'streak-100': ['Leyenda del club', 'Racha de 100 días'],
        fifty: ['Cincuenta', 'Juega 50 diarios'],
        century: ['Centenario', 'Juega 100 diarios'],
        'tenable-ten': ['Pleno', '10/10 en Tenable'],
        'wordle-two': ['Francotirador', 'Resuelve Wordle en 2'],
        'connections-flawless': ['Portería a cero', 'Connections sin fallos'],
        'pointless-low': ['Sabiduría oculta', 'Gana Pointless con 30 o menos'],
        'early-kickoff': ['Madrugador', 'Juega antes de las 8'],
        'late-kickoff': ['Trasnochador', 'Juega después de las 23'],
        'top-ten': ['Top 10%', 'Supera al 90% en un diario'],
        messenger: ['Mensajero', 'Comparte un resultado'],
        recruiter: ['Ojeador', 'Comparte 5 resultados'],
        'derby-win': ['Día de derbi', 'Gana un cara a cara'],
        'derby-king': ['Rey del derbi', '10 victorias cara a cara'],
        gaffer: ['Míster', 'Crea una liga'],
        champion: ['Campeones', 'Gana una semana de liga'],
      },
    },
    me: {
      title: 'Tu vestuario',
      subtitle: 'Tus rachas, récords, rivales y ligas',
      nickname: 'Tu nombre', nicknamePh: 'p. ej. Tom',
      nicknameHelp: 'Lo verán tus amigos en retos y ligas.',
      save: 'Guardar', saved: 'Guardado',
      streak: 'Racha de jornadas',
      thisWeek: 'Esta semana', pts: 'pts', played: 'jugados', perfect: 'días perfectos',
      calendar: 'Últimas 16 semanas', less: 'Menos', more: 'Más',
      records: 'Récords',
      recGame: 'Juego', recPlayed: 'J', recWin: '% vict.', recBest: 'Mejor', recAvg: 'Media', recStreak: 'Racha',
      recTop: 'Mejor %',
      noRecords: 'Juega un diario y tus récords empezarán aquí.',
      rivals: 'Cara a cara',
      rivalsEmpty: 'Cuando un amigo te envíe un resultado, aparecerá aquí con vuestro historial.',
      rivalsW: 'G', rivalsD: 'E', rivalsL: 'P', rivalsPending: '{n} por jugar',
      leagues: 'Tus ligas',
      openLeagues: 'Ligas →',
      transfer: 'Pasar a otro dispositivo',
      transferBody: 'Tus estadísticas viven en este navegador. Crea un código para llevar rachas, récords, rivales y ligas a otro dispositivo.',
      makeCode: 'Crear código',
      codeReady: 'Abre este enlace en el otro dispositivo (válido 24 horas):',
      codeShort: 'O introduce este código en la página Tú del otro dispositivo:',
      codeLong: 'Sin conexión: copia este enlace:',
      copyLink: 'Copiar enlace',
      enterCode: '¿Tienes un código?', enterPh: 'ABC123', importBtn: 'Importar',
      importConfirm: '¿Traer estadísticas de otro dispositivo? Se combinarán con las de este.',
      imported: '{n} resultados importados',
      importFailed: 'Ese código no funciona: puede haber caducado',
      reminder: 'Recordatorio diario',
    },
    leagues: {
      title: 'Ligas',
      subtitle: 'Una clasificación semanal privada para ti y tus amigos. Puntos de cada diario, se reinicia cada lunes.',
      mine: 'Tus ligas',
      none: 'Aún no estás en ninguna liga.',
      create: 'Crear una liga', createPh: 'Nombre, p. ej. Oficina FC', createBtn: 'Crear',
      join: 'Unirse con código', joinPh: 'Código', joinBtn: 'Unirse',
      needName: 'Elige primero un nombre: es lo que verán tus amigos.',
      namePh: 'Tu nombre',
      invite: 'Invitar', inviteCopied: 'Invitación copiada: pégala en el grupo',
      inviteText: 'Únete a mi liga de Triviverse "{name}" ⚽ Trivia de fútbol diaria, clasificación semanal, gratis. Código {code}',
      code: 'Código',
      week: 'Esta semana', today: 'Hoy', allTime: 'Histórico', lastWeek: 'Semana pasada',
      pos: 'Pos', player: 'Jugador', pts: 'Pts', p: 'J', w: 'G', perfect: '★',
      you: 'tú',
      rank: '{rank} de {n}',
      ptsBehind: 'a {n} pts del líder', leading: 'Líder', level: 'Empatado arriba',
      nextUp: '{n} pts para alcanzar a {name}',
      champion: 'Campeón de la semana pasada',
      notPlayed: 'Aún no ha jugado',
      resetsIn: 'Se reinicia el lunes',
      joinTitle: 'Te han invitado',
      joinBody: '{n} jugadores · clasificación semanal · puntos de cada diario',
      joinCta: 'Unirse a la liga',
      notFound: 'No hay ninguna liga con ese código.',
      leave: 'Salir de la liga', leaveConfirm: '¿Salir de esta liga? Tus puntos quedan en su historial.',
      offline: 'Las ligas necesitan conexión. Tus partidas siguen contando aquí.',
      scoring: 'Puntos: 10 por diario jugado, 25 por victoria, +5 por día de racha (máx. +25), el día perfecto duplica.',
      members: '{n} jugadores',
      open: 'Abrir',
      gamesToday: 'Diarios de hoy',
    },
    errors: {
      name_required: 'Elige primero un nombre.',
      league_name_required: 'Ponle nombre a la liga.',
      too_many_leagues: 'Has creado el máximo de ligas.',
      too_many_memberships: 'Estás en el máximo de ligas.',
      league_full: 'Esa liga está llena.',
      not_found: 'No encontrado.',
      generic: 'Algo ha fallado: inténtalo de nuevo.',
    },
  },
}
